#!/usr/bin/python2.4 -i

import os
import sys
import time
import traceback

import lirc

import gobject
try:
    gobject.threads_init()
except:
    print "WARNING: gobject doesn't have threads_init, no threadsafety"

import gst

from dvdplayer import *

#scheduler_factory_set_default_name ('fairpth')
scheduler_factory_set_default_name ('fairgthread')

def remote():
    global player

    remote = lirc.LIRC("seamless")

    cmd = remote.get()
    while cmd != 'off' and cmd != 'leave':
        print >> sys.stderr, 'Command:', cmd
        try:
            getattr(player, cmd)()
        except:
            traceback.print_exc()
        cmd = remote.get()

    remote.close()

    if cmd == 'off':
        st()

def st():
    player.stop()
    while player.get_state() != gst.STATE_NULL:
        time.sleep(0,1)
    sys.exit(0)

player = DVDPlayer('player')
player.start()

remote()

# Local Variables:
# mode: Python
# End:
